export enum AccionAuditoria {
  CREAR = 'CREAR',
  ACTUALIZAR = 'ACTUALIZAR',
  ELIMINAR = 'ELIMINAR',
  ELIMINAR_PERMANENTE = 'ELIMINAR_PERMANENTE',
  CERRAR = 'CERRAR',
  RESTAURAR = 'RESTAURAR',
  CONFIRMAR = 'CONFIRMAR',
}
