export enum EntidadAuditoria {
  PERIODO = 'PERIODO',
  EMPLEADO = 'EMPLEADO',
  SALARIO = 'SALARIO',
  CONFIGURACION = 'CONFIGURACION',
  FERIADO = 'FERIADO',
  TIPO_HORA_EXTRA = 'TIPO_HORA_EXTRA',
  REGISTRO_HORAS = 'REGISTRO_HORAS',
  IMPORTACION = 'IMPORTACION',
  USUARIO = 'USUARIO',
  TURNO = 'TURNO',
  ASIGNACION_TURNO = 'ASIGNACION_TURNO',
}
